/** Don't edit this file! It has been generated automatically. */

export const EXAMPLES = {
  'accordion-simple-example' : {
    title: 'Базовый компонент',
    packagePath: 'accordion',
    moduleName: 'AccordionExampleModule',
    componentName: 'AccordionSimpleExample',
    selector: 'accordion-simple-example',
    files: ['accordion-simple-example.html','accordion-simple-example.scss','accordion-simple-example.ts'],
    loadAsync: () => import('../../pages/accordion/examples'),
  },
  'chart-simple-bar' : {
    title: 'Базовый график',
    packagePath: 'bars',
    moduleName: 'BarChartExampleModule',
    componentName: 'ChartSimpleBarComponent',
    selector: 'chart-simple-bar',
    files: ['chart-simple-bar.component.html','chart-simple-bar.component.scss','chart-simple-bar.component.ts'],
    loadAsync: () => import('../../pages/bars/examples'),
  },
  'button-icon-example' : {
    title: 'Иконки',
    packagePath: 'button',
    moduleName: 'ButtonExampleModule',
    componentName: 'ButtonIconExample',
    selector: 'button-icon-example',
    files: ['button-icon-example.html','button-icon-example.scss','button-icon-example.ts'],
    loadAsync: () => import('../../pages/button/examples'),
  },
  'button-size-example' : {
    title: 'Размер',
    packagePath: 'button',
    moduleName: 'ButtonExampleModule',
    componentName: 'ButtonSizeExample',
    selector: 'button-size-example',
    files: ['button-size-example.html','button-size-example.scss','button-size-example.ts'],
    loadAsync: () => import('../../pages/button/examples'),
  },
  'button-style-example' : {
    title: 'Стиль',
    packagePath: 'button',
    moduleName: 'ButtonExampleModule',
    componentName: 'ButtonStyleExample',
    selector: 'button-style-example',
    files: ['button-style-example.html','button-style-example.scss','button-style-example.ts'],
    loadAsync: () => import('../../pages/button/examples'),
  },
  'checkbox-simple-example' : {
    title: 'Базовый компонент',
    packagePath: 'checkbox',
    moduleName: 'CheckboxExampleModule',
    componentName: 'CheckboxSimpleExample',
    selector: 'checkbox-simple-example',
    files: ['checkbox-simple-example.html','checkbox-simple-example.ts'],
    loadAsync: () => import('../../pages/checkbox/examples'),
  },
  'input-native-example' : {
    title: 'Нативные контроллы',
    packagePath: 'input',
    moduleName: 'InputExampleModule',
    componentName: 'InputNativeExample',
    selector: 'input-native-example',
    files: ['input-native-example.html','input-native-example.scss','input-native-example.ts'],
    loadAsync: () => import('../../pages/input/examples'),
  },
  'input-simple-example' : {
    title: 'Базовый компонент',
    packagePath: 'input',
    moduleName: 'InputExampleModule',
    componentName: 'InputSimpleExample',
    selector: 'input-simple-example',
    files: ['input-simple-example.html','input-simple-example.scss','input-simple-example.ts'],
    loadAsync: () => import('../../pages/input/examples'),
  },
  'range-simple-example' : {
    title: 'Базовый компонент',
    packagePath: 'range',
    moduleName: 'RangeExampleModule',
    componentName: 'RangeSimpleComponent',
    selector: 'range-simple-example',
    files: ['range-simple-example.html','range-simple-example.scss','range-simple-example.ts'],
    loadAsync: () => import('../../pages/range/examples'),
  },
  'select-simple-example' : {
    title: 'Базовый компонент',
    packagePath: 'select',
    moduleName: 'SelectExampleModule',
    componentName: 'SelectSimpleExample',
    selector: 'select-simple-example',
    files: ['select-simple-example.html','select-simple-example.scss','select-simple-example.ts'],
    loadAsync: () => import('../../pages/select/examples'),
  },
  'slider-simple-example' : {
    title: 'Базовый компонент',
    packagePath: 'slider',
    moduleName: 'SliderExampleModule',
    componentName: 'SliderSimpleComponent',
    selector: 'slider-simple-example',
    files: ['slider-simple-example.html','slider-simple-example.scss','slider-simple-example.ts'],
    loadAsync: () => import('../../pages/slider/examples'),
  },
  'spinner-simple-example' : {
    title: 'Базовый компонент',
    packagePath: 'spinner',
    moduleName: 'SpinnerExampleModule',
    componentName: 'SpinnerSimpleComponent',
    selector: 'spinner-simple-example',
    files: ['spinner-simple-example.html','spinner-simple-example.ts'],
    loadAsync: () => import('../../pages/spinner/examples'),
  },
  'tabs-simple-example' : {
    title: 'Базовый компонент',
    packagePath: 'tabs',
    moduleName: 'TabsExampleModule',
    componentName: 'TabsSimpleExample',
    selector: 'tabs-simple-example',
    files: ['lorem.ts','tabs-simple-example.html','tabs-simple-example.scss','tabs-simple-example.ts'],
    loadAsync: () => import('../../pages/tabs/examples'),
  },
  'toggle-simple-example' : {
    title: 'Базовый компонент',
    packagePath: 'toggle',
    moduleName: 'ToggleExampleModule',
    componentName: 'ToggleSimpleExample',
    selector: 'toggle-simple-example',
    files: ['toggle-simple-example.html','toggle-simple-example.ts'],
    loadAsync: () => import('../../pages/toggle/examples'),
  },
  'toggle-size-example' : {
    title: 'Размеры',
    packagePath: 'toggle',
    moduleName: 'ToggleExampleModule',
    componentName: 'ToggleSizeExample',
    selector: 'toggle-size-example',
    files: ['toggle-size-example.html','toggle-size-example.scss','toggle-size-example.ts'],
    loadAsync: () => import('../../pages/toggle/examples'),
  },
  'typography-header-example' : {
    title: 'Заголовок',
    packagePath: 'typography',
    moduleName: 'TypographyExampleModule',
    componentName: 'TypographyHeaderExample',
    selector: 'typography-header-example',
    files: ['typography-header-example.html','typography-header-example.ts'],
    loadAsync: () => import('../../pages/typography/examples'),
  },
  'typography-link-example' : {
    title: 'Ссылка',
    packagePath: 'typography',
    moduleName: 'TypographyExampleModule',
    componentName: 'TypographyLinkExample',
    selector: 'typography-link-example',
    files: ['typography-link-example.html','typography-link-example.ts'],
    loadAsync: () => import('../../pages/typography/examples'),
  }
};