export const KRUI_CHART_COLORS_LIST = [
  'var(--color-logo)',
  'var(--color-index-green)',
  'var(--color-index-red)',
  'var(--color-index-yellow)',
  'var(--color-index-gray)',
  'var(--color-index-blue)',
  'var(--color-additional-1)',
  'var(--color-additional-2)',
  'var(--color-additional-3)',
  'var(--color-additional-4)',
  'var(--color-additional-5)',
  'var(--color-additional-6)',
  'var(--color-additional-7)',
  'var(--color-additional-8)',
  'var(--color-additional-9)',
  'var(--color-additional-10)',
  'var(--color-additional-11)',
  'var(--color-additional-12)',
  'var(--color-additional-13)',
  'var(--color-additional-14)',
  'var(--color-additional-15)',
  'var(--color-additional-16)',
  'var(--color-additional-17)',
  'var(--color-additional-18)',
  'var(--color-additional-19)',
  'var(--color-additional-20)',
  'var(--color-additional-21)',
];

export const KRUI_CHART_AXIS_COLORS_LIST = [
  'var(--color-borders-light)',
  'var(--color-color-12)',
  'var(--color-color-13)',
  'var(--color-color-14)',
  'var(--color-color-15)',
  'var(--color-color-16)',
  'var(--color-color-17)',
  'var(--color-color-18)',
  'var(--color-color-19)',
];

export const KRUI_CHART_GRID_COLORS_LIST = [
  'var(--color-borders-light)',
  'var(--color-color-8)',
  'var(--color-color-9)',
  'var(--color-color-10)',
  'var(--color-color-11)',
  'var(--color-color-12)',
  'var(--color-color-13)',
  'var(--color-color-14)',
  'var(--color-color-15)',
];

