export const KRUI_CHART_COLORS_LIST = [
  'var(--color-logo)',
  'var(--color-index-plan)',
  'var(--color-index-green)',
  'var(--color-index-deviation)',
  'var(--color-index-critical)',
  'var(--color-predictors-1)',
  'var(--color-predictors-2)',
  'var(--color-predictors-3)',
  'var(--color-predictors-4)',
  'var(--color-predictors-5)',
  'var(--color-predictors-6)',
  'var(--color-predictors-7)',
  'var(--color-predictors-8)',
  'var(--color-predictors-9)',
  'var(--color-predictors-10)',
  'var(--color-predictors-11)',
];

export const KRUI_CHART_AXIS_COLORS_LIST = [
  'var(--color-borders-and-icons-icons)',
  'var(--color-color-12)',
  'var(--color-color-13)',
  'var(--color-color-14)',
  'var(--color-color-15)',
  'var(--color-color-16)',
  'var(--color-color-17)',
  'var(--color-color-18)',
  'var(--color-color-19)',
  'var(--color-borders-and-icons-icons)',
  'var(--color-text-optional-color)',
  'var(--color-text-signatures-and-future)',
  'var(--color-text-white-on-color)',
  'var(--color-text-contrast)',
  'var(--color-index-fact-or-low)',
  'var(--color-color-11)',
  'var(--color-color-10',
];

export const KRUI_CHART_GRID_COLORS_LIST = [
  'var(--color-borders-and-icons-stroke-shape)',
  'var(--color-color-8)',
  'var(--color-color-9)',
  'var(--color-color-10)',
  'var(--color-color-11)',
  'var(--color-color-12)',
  'var(--color-color-13)',
  'var(--color-color-14)',
  'var(--color-color-15)',
  'var(--color-color-16)',
  'var(--color-color-17)',
  'var(--color-color-18)',
  'var(--color-color-19)',
  'var(--color-color-4)',
  'var(--color-color-6)',
  'var(--color-color-7)',
  'var(--color-borders-and-icons-stroke-shape)',
];

